# -*- coding: utf-8 -*-
"""pandas1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJrab1ySRVRgnwswxua9Y9ydzaNbmL-k
"""

3+4

import pandas as pd

"""pd can be any name"""

df=pd.read_csv('Salaries.csv')

df

df.head()

df.tail()

df.head(8)

df.shape

df.columns

df.dtypes

df.info()

df.isnull()

pd.set_option('display.max_rows',None)

df

df.isnull()

df.isnull().sum()

df.describe()

df['salary']

df['salary'].mean()

df['salary'].median()

df['salary'].mode()

df['salary'].var()

df['salary'].std()

df['salary'].max()

df['salary'].min()

df['salary'].skew()

df['salary'].kurt()

df[['salary','service']]

df[['salary','service']].mean()

df.mean()

import warnings
warnings.filterwarnings('ignore')
df.mean()

df['salary']>120000

df[df['salary']>120000]

df.max()

df['rank'].value_counts()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df1=pd.read_csv('Universities.csv')

df1

plt.figure(figsize=(5,5))
plt.hist(df1['Accept'])
plt.xlabel('accept')
plt.ylabel('count')
plt.title('histogram of accept')
plt.show()

plt.figure(figsize=(5,5))
plt.hist(df1['SAT'])
plt.xlabel('sat')
plt.ylabel('count')
plt.title('histogram of sat')
plt.show()

oxplot()

sns.histplot(df1['Accept'])

sns.distplot(df1['Accept'])

sns.distplot(df1['SAT'])

import warnings
warnings.filterwarnings('ignore')
sns.distplot(df1['SAT'])

r+ gives red colour +
ro gives red colour o

plt.plot(df1['Accept'],df1['Expenses'],'go')

sns.pairplot(df1)

df.iloc[:,:]

df.iloc[0:10,:]

df1.iloc[0:10,0:3]

df1.iloc[0:10,[0,3,4]]

plt.boxplot(df1['Accept'])

df1.describe()

df1['Accept'].describe()

plt.boxplot(df1['Accept'],vert=False)

plt.boxplot(df1['Accept'],vert=False)
plt.show()

